### ISSUE TITLE
subtitles in music

### ISSUE THREAD

**Issue by howudodat** [allejok96/plugin.video.jwb-unofficial#5]
I cant seem to turn them off.  If while playing the video I go to subtitles, it shows off, if I go to plugin settings, it shows turned off.  happens with music in french

**Comment by howudodat** [comment]
never mind.  there seem to be some videos with burnt in captions.

**Comment by allejok96** [comment]
This could be a bug. If you'd watch it on the.jw.org, is it impossible to turn off subtitles?

There's sometimes 2 video streams (subs and no subs) and the add-on should select the right one depending on the Subtitles setting. This has been broken from time to time, so please make sure you have JWB 1.11.3 ... I think was the latest.... if you're testing.

Note: that setting is *only* for burnt in subtitles, since soft coded ones is a global Kodi setting, and there's no way I know to set this for a single video.

**Comment by allejok96** [comment]
Huh I looked over at the French page, and it's just the way it is... There's a bit of a mess in this area. Some English videos has both soft and hard subtitles. Some French has only hard. Other languages have only soft... Well, at least now we know that. (And I agree - subtitles are annoying, especially for songs!)
