### ISSUE TITLE
Add "Play random video" feature

### ISSUE THREAD

**Issue by konuch** [allejok96/plugin.video.jwb-unofficial#7]
Hello, in old JW Broadcasting, before it was transitioned to jw.org, there was a feature to play random videos from website. It was like a live stream. On jw.org this feature is not available anymore.
Would it be too complicated to introduce this feature into this addon?

PS. Thanks for good work!

**Comment by allejok96** [comment]
Seems like they removed all the "Streaming channel" infrastructure in favor of a button that simply plays all videos in random order. Which makes sense. Having streaming channels that are synced up all across the globe was cool, but pointless.

Good news is it makes things even simpler, and I have pushed out an update which adds a Shuffle option in the context menu of each of the categories (and sub-categories too, yay).

PS in worst case some videos may be played twice in a row. I have the fix for it, but I'm too lazy to push out another update, so it will just have to wait until something more comes up.

**Comment by konuch** [comment]
Thanks a lot for this update. It's exactly what we were looking for.  :)
Have a nice day
